Repository eclipse-edc/MinimumViableDataspace, pull requests merged in 2022-12, with the labels that each got.

#105 feat(workflows): add discord webhook for issues, discussions and pull requests
  .github/workflows/discord-webhook.yml
Labels: no-changelog

#108 fix: compile error due to Nimubs upgrade
  system-tests/src/test/java/org/eclipse/edc/system/tests/identityhub/IdentityHubIntegrationTest.java
Labels: bug

#110 fix(docs): resolve markdown syntax errors
  system-tests/README.md
Labels: documentation

#111 build: upgrade the Gradle version to 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build
