Repository eclipse-edc/MinimumViableDataspace, pull requests merged in 2024-07, with the labels that each got.

#278 doc: link in README.md fixed
  README.md
Labels: documentation

#279 feat(api): add version API to connector runtimes
  gradle/libs.versions.toml
  launchers/connector/build.gradle.kts
Labels: enhancement

#280 feat: environment file for HTTP Client plugin (IntelliJ)
  README.md
  deployment/postman/http-client.env.json
Labels: enhancement

#285 chore: consistent case for X-Api-Key in postman collection
  deployment/postman/MVD.postman_collection.json
Labels: documentation

#286 feat: creates All-In-One runtimes for use with IntelliJ
  .run/Connector Consumer Corp.run.xml
  .run/Connector _provider-manufacturing_.run.xml
  .run/Connector _provider-qna_.run.xml
  .run/IdentityHub Consumer Corp.run.xml
  .run/IdentityHub Provider Corp.run.xml
  .run/Provider Catalog Server.run.xml
  README.md
  deployment/assets/consumer_private.pem
  deployment/assets/consumer_public.pem
  deployment/assets/credentials/local/consumer/alice-membership-credential.json
  deployment/assets/credentials/local/consumer/alice-pcf-credential.json
  deployment/assets/credentials/local/consumer/membership_vc.json
  deployment/assets/credentials/local/consumer/pcf_vc.json
  deployment/assets/credentials/local/provider/bob-membership-credential.json
  deployment/assets/credentials/local/provider/bob-pcf-credential.json
  deployment/assets/credentials/local/provider/membership_vc.json
  deployment/assets/credentials/local/provider/pcf_vc.json
  deployment/assets/env/consumer_connector.env
  deployment/assets/env/consumer_identityhub.env
  deployment/assets/env/provider_catalogserver.env
  deployment/assets/env/provider_connector_manufacturing.env
  deployment/assets/env/provider_connector_qna.env
  deployment/assets/env/provider_identityhub.env
  deployment/assets/provider_private.pem
  deployment/assets/provider_public.pem
  launchers/runtime-embedded/build.gradle.kts
  seed.sh
  settings.gradle.kts
Labels: enhancement, build

#287 fix: remove spaces around = in env files
  deployment/assets/env/consumer_connector.env
  deployment/assets/env/provider_connector_manufacturing.env
  deployment/assets/env/provider_connector_qna.env
Labels: bug

#290 feat: add FC Cache Postgres modules
  deployment/assets/postgres/edc_schema.sql
  gradle/libs.versions.toml
  launchers/controlplane/build.gradle.kts
Labels: enhancement

#288 feat(docs): update postman collection and deployment scripts for Asset transfer
  README.md
  deployment/assets/credentials/local/consumer/unsigned/membership_vc.json
  deployment/assets/credentials/local/consumer/unsigned/pcf_vc.json
  deployment/assets/credentials/local/provider/unsigned/membership_vc.json
  deployment/assets/credentials/local/provider/unsigned/pcf_vc.json
  deployment/assets/postgres/edc_schema.sql
  deployment/modules/catalog-server/catalog-server.tf
  deployment/modules/connector/controlplane.tf
  deployment/modules/connector/dataplane.tf
  deployment/postman/MVD.postman_collection.json
  gradle.properties
  gradle/libs.versions.toml
  launchers/dataplane/build.gradle.kts
  launchers/identity-hub/build.gradle.kts
  seed-k8s.sh
Labels: documentation, build

#294 feat(test): adds E2E tests to the CI
  .github/workflows/run-terraform.yml
  .github/workflows/verify.yaml
  gradle/libs.versions.toml
  settings.gradle.kts
  tests/end2end/build.gradle.kts
  tests/end2end/src/test/java/org/eclipse/edc/demo/tests/transfer/TransferEndToEndTest.java
  tests/end2end/src/test/resources/negotiation-request.json
  tests/end2end/src/test/resources/transfer-request.json
  tests/system-tests/build.gradle.kts
Labels: enhancement, build

#295 feat(ci): improve CI workflows
  .github/dependabot.yml
  .github/workflows/run-terraform.yml
  .github/workflows/stale-bot.yml
  deployment/assets/postgres/edc_schema.sql
  deployment/postman/management_api_tests.json
  tests/end2end/src/test/java/org/eclipse/edc/demo/tests/transfer/TransferEndToEndTest.java
Labels: enhancement

#307 docs(readme): improve README
  .github/dependabot.yml
  README.md
  extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DcpPatchExtension.java
  extensions/dcp-impl/src/main/java/org/eclipse/edc/demo/dcp/core/DefaultScopeMappingFunction.java
Labels: documentation
